name: Manual - Patch Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version to Release ie 1.2.3'    
        required: true
        default: 'x.y.z'
      nextVersion:
        description: 'Version to Release ie 1.2.4'    
        required: true
        default: 'x.y.z+1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD

    - name: Patch Release with Maven
      shell: bash
      run: |
        echo "Releasing Version"
        echo ${releaseVersion}
        git config --global user.name "ais-swe-ci"
        git config --global user.email "aitci@psu.edu"
        git checkout develop
        echo -n $SIGNING_PRIVATE | base64 -di > ~/private.asc
        gpg --pinentry-mode loopback --batch --no-tty --yes --passphrase $SIGNING_PASSPHRASE --import ~/private.asc
        mvn -B clean build-helper:parse-version jgitflow:release-start -DreleaseVersion=${releaseVersion} -DdevelopmentVersion=${nextVersion}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        mvn -B jgitflow:release-finish -Dgpg.passphrase=$SIGNING_PASSPHRASE -DreleaseVersion=${releaseVersion} -DdevelopmentVersion=${nextVersion}-SNAPSHOT -DallowUntracked=true -DallowSnapshots=false -DallowUntracked=true -Psign-artifacts
        git checkout develop
        git commit --amend -m '[skip-ci] Updating develop poms back to pre merge state'
        git push --all --follow-tags
      env:
        SIGNING_PRIVATE: ${{secrets.SIGNING_PRIVATE}}
        SIGNING_PASSPHRASE: ${{secrets.SIGNING_PASSPHRASE}}
        OSSRH_USERNAME: aitci
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
        releaseVersion: ${{github.event.inputs.releaseVersion}}
        nextVersion: ${{github.event.inputs.nextVersion}}

    # TODO: add steps to:
    # - Version POMs
    # - Update POM to next Snapshot version (on develop branch)
    # - Add released artifacts to the release (publish) that started this build
