name: CI
on: push
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        SUPER_SECRET=${{ secrets.DOMS_DUMMY_SECRET }}
        echo ${{ secrets.DOMS_DUMMY_SECRET }}
        echo $SUPER_SECRET
        echo ${{ secrets.DOMS_DUMMY_SECRET }} | base64
        echo test, and deploy your project.
